<?php
if(function_exists("register_field_group"))
{
  register_field_group(array (
    'id' => 'acf_service-page-fields',
    'title' => 'Service Page Fields',
    'fields' => array (
      array (
        'key' => 'field_54a619caf675f',
        'label' => 'Secondary Title',
        'name' => 'servicepage_secondary_title',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_54a619dff6760',
        'label' => 'Featured Image',
        'name' => 'servicepage_featured_image',
        'type' => 'image',
        'save_format' => 'url',
        'preview_size' => 'thumbnail',
        'library' => 'all',
      ),
      array (
        'key' => 'field_54a619f4f6761',
        'label' => 'Content',
        'name' => 'servicepage_content',
        'type' => 'wysiwyg',
        'default_value' => '',
        'toolbar' => 'full',
        'required' => 1,
        'media_upload' => 'yes',
      ),
      array (
        'key' => 'field_54a61a00f6762',
        'label' => 'CTA Ribbon Text',
        'name' => 'servicepage_cta_ribbon_text',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'required' => 1,
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_54a61a0cfwrg3g56763',
        'label' => 'CTA Text Title',
        'name' => 'servicepage_cta_text_title',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'required' => 1,
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_54a61a0cf6763',
        'label' => 'CTA Text',
        'name' => 'servicepage_cta_text',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'required' => 1,
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_54a61a35f6764',
        'label' => 'CTA Button Text',
        'name' => 'servicepage_cta_button_text',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'required' => 1,
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_54a619hbdau8caf675f',
        'label' => 'CTA Contact Form Title',
        'name' => 'service_page_cta_form_title',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_54ddda619hbdau8caf675f',
        'label' => 'CTA Contact Form Sub Title',
        'name' => 'service_page_cta_form_sub_title',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_54a61a3ef6765',
        'label' => 'CTA Contact Form Code',
        'name' => 'servicepage_contact_form_contact_code',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'required' => 1,
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'page-service.php',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'acf_after_title',
      'layout' => 'default',
      'hide_on_screen' => array (
        0 => 'the_content',
      ),
    ),
    'menu_order' => 0,
  ));
}
