<?php
if(function_exists("register_field_group"))
{
  register_field_group(array (
    'id' => 'acf_white-paper-fields',
    'title' => 'White Paper Fields',
    'fields' => array (
      array (
        'key' => 'field_54a656e973d28',
        'label' => 'Secondary Title',
        'name' => 'wp_secondary_title',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_nhwibviw54a619dff6760',
        'label' => 'Featured Image',
        'name' => 'wp_featured_image',
        'type' => 'image',
        'save_format' => 'url',
        'preview_size' => 'thumbnail',
        'library' => 'all',
      ),
      array (
        'key' => 'field_54a6570273d29',
        'label' => 'Content',
        'name' => 'wp_content',
        'type' => 'wysiwyg',
        'default_value' => '',
        'toolbar' => 'full',
        'media_upload' => 'yes',
      ),
      array (
        'key' => 'field_54a6571673d2a',
        'label' => 'Form Title',
        'name' => 'wp_form_title',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_54a6575073d2b',
        'label' => 'Form Secondary Title',
        'name' => 'wp_form_secondary_title',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_54a6578673d2c',
        'label' => 'Form Contact Shortcode',
        'name' => 'form_contact_shortcode',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'page-white-paper.php',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'acf_after_title',
      'layout' => 'default',
      'hide_on_screen' => array (
        0 => 'the_content',
      ),
    ),
    'menu_order' => 0,
  ));
}
